--! @file
--! @brief Programmable timer with prescaler and restart capability.
--! @details Generates a one-cycle `is_timer_end` pulse when the counter overflows. Supports runtime updates of prescale factor and start value, and a synchronous restart.
library IEEE;
  use IEEE.STD_LOGIC_1164.all;
  use IEEE.NUMERIC_STD.all;

--! \defgroup UNIT ExtPack units
--! @brief Standard units of ExtPack.
--! @{

--! Parameterizable timer that counts on a prescaled enable and signals end-of-period.
entity Timer_Unit is
--! @}
  generic (
    WIDTH : integer := 8; --! Counter width in bits.
    IN_FREQ : integer := 12000000; --! Input clock frequency in Hz.
    BASE_FREQ : integer := 50000 --! Base tick frequency in Hz before prescaling.
  );
  port (
    clk : in std_logic; --! Clock signal.
    rst : in std_logic; --! Reset signal.
    en : in std_logic; --! Global enable for the timer.
    prescale_factor_write_en : in std_logic; --! Latch a new prescale_factor on '1'.
    prescale_factor : in integer; --! Multiplier applied to BASE_FREQ divider.
    start_value_write_en : in std_logic; --! Latch a new start_value on '1'.
    start_value : in unsigned(WIDTH-1 downto 0); --! Counter reload/start value.
    restart_timer : in std_logic; --! Synchronous restart pulse.
    is_timer_end : out std_logic --! One-cycle pulse when the counter overflows.
  );
end entity;

--! Architecture implementing prescaler, registers for runtime configuration, and the timer FSM.
architecture Behavioral of Timer_Unit is
  --! Default prescaler terminal count derived from IN_FREQ/BASE_FREQ.
  constant PRESCALE_COUNTER_END_DEFAULT : integer := IN_FREQ / BASE_FREQ;
  --! Terminal counter value that triggers is_timer_end (all ones).
  constant is_timer_end_value : unsigned(WIDTH-1 downto 0) := (others => '1');
  --! Current counter value.
  signal timer_counter : unsigned(WIDTH-1 downto 0) := (others => '0');
  --! Latched start value used after overflow/restart.
  signal start_value_int :unsigned(WIDTH-1 downto 0) := (others => '0');
  --! Current prescaler terminal count (can be updated at runtime).
  signal prescale_counter_end : integer := PRESCALE_COUNTER_END_DEFAULT;
  --! Prescaler counter incremented each clock.
  signal prescale_counter : integer := 1;
  --! One-cycle enable generated by the prescaler when terminal count is reached.
  signal clk_en_prescaled : std_logic := '0';
  --! Internal synchronous reset for the timer (rst or restart_timer).
  signal timer_rst : std_logic := '0';
begin

  --! Prescaler process: generates a one-cycle enable every `prescale_counter_end` clocks.
  PRESCALER: process(clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        -- Reset prescaler and clear enable.
        clk_en_prescaled <= '0';
        prescale_counter <= 0;
      else
        prescale_counter <= prescale_counter + 1;
        clk_en_prescaled <= '0';
        if prescale_counter >= prescale_counter_end then 
          clk_en_prescaled <= '1';
          prescale_counter <= 1;
        end if;
      end if;
    end if;
  end process;

  --! Internal timer reset: asserted when global reset or restart is active.
  timer_rst <= rst or restart_timer;

  --! Configuration register process: latches prescale factor and start value when write-enables are asserted.
  REG: process(clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        start_value_int <= (others => '0');
        prescale_counter_end <= PRESCALE_COUNTER_END_DEFAULT;
      else
        if prescale_factor_write_en = '1' then
          -- Latch new prescale factor.
          prescale_counter_end <= PRESCALE_COUNTER_END_DEFAULT*prescale_factor;
        end if;
        if start_value_write_en = '1' then
          -- Latch new start value.
          start_value_int <= start_value;
        end if;
      end if;
    end if;
  end process;

  --! Timer process: counts on prescaled clk and enable, reloads from start_value, and pulses is_timer_end on overflow.
  TIMER_PRESCALED: process(clk)
  begin
    if rising_edge(clk) then
      if timer_rst = '1' then
        timer_counter <= (others => '0');
        is_timer_end <= '0';
      elsif clk_en_prescaled = '1' and en = '1' then
        is_timer_end <= '0';
        if timer_counter = 0 then
          -- Overflow or reset occurred in the previous cycle.
          -- Jump to start_value (+1).
          timer_counter <= start_value_int + 1;
        else
          -- Normal counting.
          timer_counter <= timer_counter + 1;
        end if;
        -- Timer end OR start_value equals terminal value (then every enabled tick ends the timer).
        -- Explicit check ensures the start_value==all-ones case is handled.
        if (timer_counter = is_timer_end_value) or (start_value_int = is_timer_end_value) then
          -- Timer overflow.
          -- Pulse is_timer_end and reset counter to 0.
          is_timer_end <= '1';
          timer_counter <= (others => '0');
        end if;
      else
        is_timer_end <= '0';
      end if;
    end if;
  end process;
  
end architecture;
